name: shopping
description: Projeto de uma loja de venda.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: any
  dio: any
  intl: ^0.15.8
  shared_preferences: ^0.5.3
  connectivity: ^0.4.8+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/categories/light/automotivo.png
   - assets/categories/light/brinquedos.png
   - assets/categories/light/decor.png
   - assets/categories/light/eletrodomesticos.png
   - assets/categories/light/games.png
   - assets/categories/light/informatica.png
   - assets/categories/light/moda.png
   - assets/categories/light/telefonia.png
   - assets/categories/light/tv.png
   - assets/categories/dark/automotivo.png
   - assets/categories/dark/brinquedos.png
   - assets/categories/dark/decor.png
   - assets/categories/dark/eletrodomesticos.png
   - assets/categories/dark/games.png
   - assets/categories/dark/informatica.png
   - assets/categories/dark/moda.png
   - assets/categories/dark/telefonia.png
   - assets/categories/dark/tv.png
   - assets/categories/dark-yellow/automotivo.png
   - assets/categories/dark-yellow/brinquedos.png
   - assets/categories/dark-yellow/decor.png
   - assets/categories/dark-yellow/eletrodomesticos.png
   - assets/categories/dark-yellow/games.png
   - assets/categories/dark-yellow/informatica.png
   - assets/categories/dark-yellow/moda.png
   - assets/categories/dark-yellow/telefonia.png
   - assets/categories/dark-yellow/tv.png
      # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
